-- =============================================================================
-- migration-equipment-inventory.sql
-- 25 Apr 2026
--
-- Adds equipment_inventory (master catalog) and extends equipment_requests
-- with inventory_item_id + is_rental + relaxed item_type check.
--
-- Seeded with 264 rows for EHRC: 11 specialty kits (from OT_Grouped_Kits xlsx),
-- 220+ unique instruments (deduped across kits), 13 laparoscopes (from
-- Laparoscopes Tracker xlsx), and the ad-hoc surgical equipment V called out
-- in chat (Stryker Lap Tower, Holmium Laser, Covidien Cautery + Ligasure,
-- Ethicon Focus Harmonic, OT lights/tables/anaesthesia workstation, common
-- consumables).
--
-- Idempotent: CREATE TABLE IF NOT EXISTS, ALTER ADD COLUMN IF NOT EXISTS,
-- INSERTs guarded by NOT EXISTS lookup on (hospital_id, item_label).
-- =============================================================================

-- 1. equipment_inventory ------------------------------------------------------
CREATE TABLE IF NOT EXISTS equipment_inventory (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hospital_id          UUID NOT NULL REFERENCES hospitals(id),
  category             TEXT NOT NULL CHECK (category IN (
                         'surgical_equipment', 'infrastructure', 'consumable', 'kit'
                       )),
  subcategory          TEXT,
  item_label           TEXT NOT NULL,
  brand                TEXT,
  model                TEXT,
  size_spec            TEXT,
  is_rentable          BOOLEAN NOT NULL DEFAULT TRUE,
  default_vendor_name  TEXT,
  default_vendor_phone TEXT,
  notes                TEXT,
  is_active            BOOLEAN NOT NULL DEFAULT TRUE,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (hospital_id, item_label)
);

CREATE INDEX IF NOT EXISTS idx_ei_hospital_active
  ON equipment_inventory(hospital_id, is_active)
  WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_ei_category
  ON equipment_inventory(hospital_id, category, is_active);
CREATE INDEX IF NOT EXISTS idx_ei_label_search
  ON equipment_inventory USING gin (to_tsvector('english', item_label));

-- 2. equipment_requests: extend ----------------------------------------------
ALTER TABLE equipment_requests
  ADD COLUMN IF NOT EXISTS inventory_item_id UUID REFERENCES equipment_inventory(id);

ALTER TABLE equipment_requests
  ADD COLUMN IF NOT EXISTS is_rental BOOLEAN NOT NULL DEFAULT FALSE;

-- Relax item_type CHECK so users can request anything from inventory categories.
-- New constraint covers existing values + the inventory categories.
DO $relax$
BEGIN
  ALTER TABLE equipment_requests DROP CONSTRAINT IF EXISTS equipment_requests_item_type_check;
  ALTER TABLE equipment_requests
    ADD CONSTRAINT equipment_requests_item_type_check
    CHECK (item_type IN (
      'specialty', 'rental', 'implant', 'blood', 'imaging',
      'surgical_equipment', 'infrastructure', 'consumable', 'kit',
      'instrument', 'other'
    ));
EXCEPTION WHEN OTHERS THEN
  -- If constraint name differs, log and continue.
  RAISE NOTICE 'Could not replace item_type constraint cleanly: %', SQLERRM;
END
$relax$;

CREATE INDEX IF NOT EXISTS idx_er_inventory_item
  ON equipment_requests(inventory_item_id) WHERE inventory_item_id IS NOT NULL;

-- 3. Seed: 264 rows for EHRC -------------------------------------------------
-- Resolve EHRC hospital_id once.
DO $seed$
DECLARE
  v_ehrc_id UUID;
BEGIN
  SELECT id INTO v_ehrc_id FROM hospitals WHERE slug = 'ehrc' LIMIT 1;
  IF v_ehrc_id IS NULL THEN
    RAISE EXCEPTION 'EHRC hospital not found (slug=ehrc)';
  END IF;


  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'Proctology Kit', NULL, NULL, TRUE, 'OT: OT 1 (Dirty / Bottom Cases) · Covers: Piles, Anal Fissure (LIS), Anal Fistula, Pilonidal Sinus, Perianal Abscess · Min qty: 3 · Sterilization: Steam Autoclave — 134°C, 18 min' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Proctology Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'Circumcision Kit', NULL, NULL, TRUE, 'OT: OT 1 (Dirty / Bottom Cases) · Covers: Standard Circumcision, Stapler/ZSR Circumcision, Dorsal Slit · Min qty: 3 · Sterilization: Steam Autoclave — 134°C, 18 min' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Circumcision Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'Lap GenSurg Kit', NULL, NULL, TRUE, 'OT: OT 2 (Multipurpose) · Covers: Lap Hernia (TEP/TAPP), Lap Cholecystectomy, Lap Appendectomy · Min qty: 2 · Sterilization: Steam Autoclave — 134°C, 18 min' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Lap GenSurg Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'Minor-Open Surg Kit', NULL, NULL, TRUE, 'OT: OT 2 (Multipurpose) · Covers: Lipoma, WLE, Cyst Excision, Lymph Node Excision, Hydrocele, Minor Skin/Subcut · Min qty: 2 · Sterilization: Steam Autoclave — 134°C, 18 min' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Minor-Open Surg Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'Vascular Kit', NULL, NULL, TRUE, 'OT: OT 2 (Multipurpose) · Covers: Varicose Veins, EVLA, Sclerotherapy, Phlebectomy, VenaSeal · Min qty: 1 · Sterilization: Steam Autoclave — 134°C, 18 min' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Vascular Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'ENT Kit', NULL, NULL, TRUE, 'OT: OT 2 (Multipurpose) · Covers: Septoplasty, Turbinoplasty, Turbinectomy, Tympanoplasty, Nasal Bone Reduction, CSF Rhinorrhea · Min qty: 1 · Sterilization: Steam Autoclave — 134°C, 18 min' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ENT Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'Ortho Joint Kit', NULL, NULL, TRUE, 'OT: OT 3 (Clean — Ortho Only) · Covers: TKR, THR, Unicondylar/Partial Knee (UKR), Revision TKR/THR · Min qty: 2 · Sterilization: Steam Autoclave — 134°C, 18 min' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Ortho Joint Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'Ortho Trauma Kit', NULL, NULL, TRUE, 'OT: OT 3 (Clean — Ortho Only) · Covers: Fracture Fixation (ORIF), ACL/PCL Reconstruction, Rotator Cuff, Revision, Nerve Surgery · Min qty: 1 · Sterilization: Steam Autoclave — 134°C, 18 min' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Ortho Trauma Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'Ortho Arthoscopy Kit Kit', NULL, NULL, TRUE, 'OT:  · Covers:  · Min qty:  · Sterilization:' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Ortho Arthoscopy Kit Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'Urology Kit', NULL, NULL, TRUE, 'OT: OT 2 (Multipurpose) · Covers: Kidney Stones (RIRS, PCNL, URS), ERCP, Ureteric Stenting, Bladder Procedures · Min qty: 1 · Sterilization: Steam Autoclave — 134°C, 18 min' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Urology Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'kit', 'kit', 'OB-Gyn Kit', NULL, NULL, TRUE, 'OT: OT (Multipurpose) / Labour Room · Covers: LSCS, Normal Delivery, D&C, Hysteroscopy, Diagnostic Lap (Gynae) · Min qty: 2 · Sterilization: Steam Autoclave — 134°C, 18 min' WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'OB-Gyn Kit');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Scalpel Handle #3', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Scalpel Handle #3');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Scalpel Handle #4', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Scalpel Handle #4');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Metzenbaum Scissors, Curved 7"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Metzenbaum Scissors, Curved 7"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Mayo Scissors, Straight 6.75"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Mayo Scissors, Straight 6.75"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Mayo Scissors, Curved 6.75"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Mayo Scissors, Curved 6.75"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Mosquito Forceps, Curved 5"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Mosquito Forceps, Curved 5"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Spencer Wells Forceps Straight 6" (as Kelly)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Spencer Wells Forceps Straight 6" (as Kelly)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Kocher Forceps, Straight 6"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Kocher Forceps, Straight 6"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Right-Angle Forceps (Mixter 8")', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Right-Angle Forceps (Mixter 8")');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Adson Tissue Forceps, Toothed', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Adson Tissue Forceps, Toothed');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Babcock Forceps 6"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Babcock Forceps 6"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Langenbeck Retractor, Medium', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Langenbeck Retractor, Medium');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Self-retaining Retractor (Balfour)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Self-retaining Retractor (Balfour)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Needle Holder, Mayo-Hegar 6"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Needle Holder, Mayo-Hegar 6"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Sponge Holder 9.5"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Sponge Holder 9.5"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Kidney Tray 10"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Kidney Tray 10"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Gallipot / Lotion Bowl 4"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Gallipot / Lotion Bowl 4"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Towel Clamp Backhaus 5"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Towel Clamp Backhaus 5"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SS Tray with Lid 12x10"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SS Tray with Lid 12x10"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'VERIFIED from Lifelinx: 19 items', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'VERIFIED from Lifelinx: 19 items');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'lignocaine jelly 1 tube', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'lignocaine jelly 1 tube');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'half proctoscope per case', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'half proctoscope per case');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'suture 2''0 vicryl round body x 2', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'suture 2''0 vicryl round body x 2');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'mops x 6', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'mops x 6');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'gauze bunches', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'gauze bunches');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'anal pack gel foam / surgicel', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'anal pack gel foam / surgicel');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'laser probe', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'laser probe');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'botroclot drops for packing', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'botroclot drops for packing');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'pause loading dose', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'pause loading dose');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ANAL RETRACTOR x 2 blade sizes from lifelinx', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ANAL RETRACTOR x 2 blade sizes from lifelinx');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'VERIFIED from Lifelinx: 17 items', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'VERIFIED from Lifelinx: 17 items');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'stapler size', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'stapler size');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'round body rapid vicril 2''0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'round body rapid vicril 2''0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'monocril (backup)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'monocril (backup)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Local without adrenalin', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Local without adrenalin');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'mops', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'mops');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'gauze', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'gauze');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'OPEN INSTRUMENTS (port site + open conversion backup)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'OPEN INSTRUMENTS (port site + open conversion backup)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SS Tray with Lid 15x12"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SS Tray with Lid 15x12"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Round Bowl / Lotion Bowl 6"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Round Bowl / Lotion Bowl 6"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'VERIFIED from Lifelinx: 16 items', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'VERIFIED from Lifelinx: 16 items');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Gauze + Mop', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Gauze + Mop');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'small retractor / small langenbacks size?', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'small retractor / small langenbacks size?');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Lap Tower', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Lap Tower');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Lap Chole', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Lap Chole');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Lap Hernia', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Lap Hernia');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Inguinal hernia', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Inguinal hernia');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Lap Appy', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Lap Appy');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'bariatric ports for heavier folks', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'bariatric ports for heavier folks');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Tissue Forceps 1:2 Teeth 6"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Tissue Forceps 1:2 Teeth 6"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Roux Retractor', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Roux Retractor');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'VERIFIED from Lifelinx: 20 items', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'VERIFIED from Lifelinx: 20 items');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'mop / gauze', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'mop / gauze');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'vicril 20', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'vicril 20');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', '20 ethilon cutting', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = '20 ethilon cutting');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'monocril', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'monocril');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'plain local', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'plain local');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'plain local plus adrenaline', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'plain local plus adrenaline');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'A V Fistula Set (Tufft Range, complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'A V Fistula Set (Tufft Range, complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'VERIFIED from Lifelinx: 12 items', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'VERIFIED from Lifelinx: 12 items');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Scalpel Handle #3 (long)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Scalpel Handle #3 (long)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Septoplasty Set (Lifelinx, 6 PCs)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Septoplasty Set (Lifelinx, 6 PCs)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Walton Malleable Spatula', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Walton Malleable Spatula');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Tonsillectomy Set (Lifelinx, 10 PCs)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Tonsillectomy Set (Lifelinx, 10 PCs)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SNG Instruments Set (Mollison)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SNG Instruments Set (Mollison)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Kidney Tray 8"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Kidney Tray 8"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'VERIFIED from Lifelinx: 13 items', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'VERIFIED from Lifelinx: 13 items');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Langenbeck Retractor, Large', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Langenbeck Retractor, Large');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Orthopaedic Instruments Set (complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Orthopaedic Instruments Set (complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'New Ortho Major Set (Tufft, complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'New Ortho Major Set (Tufft, complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Ortho Bone Lever Set (complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Ortho Bone Lever Set (complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Bone Rasp 8" (Half + Full Round)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Bone Rasp 8" (Half + Full Round)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Bone Awl', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Bone Awl');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Needle Holder, Mayo-Hegar 7"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Needle Holder, Mayo-Hegar 7"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Kidney Tray 12"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Kidney Tray 12"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Gallipot / Round Bowl 6"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Gallipot / Round Bowl 6"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Pool Suction Cannula 10"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Pool Suction Cannula 10"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Consumables - B/L TKR', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Consumables - B/L TKR');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ORTHO MAJOR DRAPE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ORTHO MAJOR DRAPE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'B/L KNEE O DRAPE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'B/L KNEE O DRAPE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'IMPERVIOUS STOCKINETTE L', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'IMPERVIOUS STOCKINETTE L');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'CLING DRAPE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'CLING DRAPE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'NS FREEFLEX POUCH 1000ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'NS FREEFLEX POUCH 1000ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'POVODINE 7.5% W/V 500ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'POVODINE 7.5% W/V 500ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'IOBAN 6650 / 6640', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'IOBAN 6650 / 6640');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SURGICAL BLADE 10/11/20/22', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SURGICAL BLADE 10/11/20/22');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ANSELL GLOVES NO. 6.5', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ANSELL GLOVES NO. 6.5');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ANSELL GLOVES NO. 7.0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ANSELL GLOVES NO. 7.0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ANSELL GLOVES NO. 7.5', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ANSELL GLOVES NO. 7.5');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ANSELL GLOVES NO. 8.0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ANSELL GLOVES NO. 8.0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SURGEON GLOVES NO. 6.5', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SURGEON GLOVES NO. 6.5');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SURGEON GLOVES NO. 7.0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SURGEON GLOVES NO. 7.0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SURGEON GLOVES NO. 7.5', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SURGEON GLOVES NO. 7.5');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SURGEON GLOVES NO. 8.0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SURGEON GLOVES NO. 8.0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'PLAIN SHEET', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'PLAIN SHEET');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SKIN STAPLER', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SKIN STAPLER');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SYRINGE 50CC,20CC,10CC', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SYRINGE 50CC,20CC,10CC');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'INJ GENTAMICIN 2ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'INJ GENTAMICIN 2ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'INJ VANCOMYCIN', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'INJ VANCOMYCIN');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'CAUTERY PENCIL', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'CAUTERY PENCIL');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'VACC SUCTION', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'VACC SUCTION');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'VICRYL NO1 2421', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'VICRYL NO1 2421');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'VICRYL 2-0  2382', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'VICRYL 2-0  2382');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ETHILON 2-0 3336', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ETHILON 2-0 3336');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ETHILON 3-0 3328', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ETHILON 3-0 3328');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'STATAFIX NO-1', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'STATAFIX NO-1');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'STATAFIX 2-0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'STATAFIX 2-0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'STATAFIX MONOCRYL  3-0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'STATAFIX MONOCRYL  3-0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'BILATERAL LIMB DRAPE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'BILATERAL LIMB DRAPE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SURGEON GOWN XL', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SURGEON GOWN XL');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', '3000ML NS', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = '3000ML NS');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'FOLEYS CATHETER 14FR', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'FOLEYS CATHETER 14FR');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'URO METER', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'URO METER');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'LOX 2% GELLY', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'LOX 2% GELLY');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'STERILE WATER 10ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'STERILE WATER 10ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SOFT ROLL 6 INCH', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SOFT ROLL 6 INCH');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ROLLER BANDAGE 6 INCH', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ROLLER BANDAGE 6 INCH');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'CRAPE BANDAGE 6INCH', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'CRAPE BANDAGE 6INCH');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'GAMJEE 6"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'GAMJEE 6"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SKIN MARKER', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SKIN MARKER');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'POVODINE  10% OINTMENT', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'POVODINE  10% OINTMENT');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'KNEE BRACE S/M/L/XL/', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'KNEE BRACE S/M/L/XL/');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SPONGE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SPONGE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'R/O GAUZE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'R/O GAUZE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'PLAIN GAUZE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'PLAIN GAUZE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'POVODINE 10%  500ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'POVODINE 10%  500ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'FACE MASK', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'FACE MASK');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'MALE AND FEMALE CAP', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'MALE AND FEMALE CAP');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'EXAMINATION GLOW', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'EXAMINATION GLOW');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'HAND RUB SOLUTION BIO-CHECK 100ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'HAND RUB SOLUTION BIO-CHECK 100ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Consumables - Unilateral TKR', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Consumables - Unilateral TKR');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ORTHO ORTHO MAJOR  DRAPE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ORTHO ORTHO MAJOR  DRAPE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'KNEE O DRAPE SURGIWEAR', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'KNEE O DRAPE SURGIWEAR');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'NS FREEFELX POUCH 1000ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'NS FREEFELX POUCH 1000ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'IOBAN 6650/6640', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'IOBAN 6650/6640');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'MONOCRYLE 3-0 1326', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'MONOCRYLE 3-0 1326');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'STATAFIX NO-1  SXPP2B405', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'STATAFIX NO-1  SXPP2B405');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'STATAFIX 2-0 SXPP1B412', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'STATAFIX 2-0 SXPP1B412');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SURGEON  GOWN XL', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SURGEON  GOWN XL');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'DRESSING PAD MEDIUM', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'DRESSING PAD MEDIUM');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'POVODINE 10% 500ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'POVODINE 10% 500ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'FEMALE CAP', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'FEMALE CAP');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'MALE CAP', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'MALE CAP');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'KNEE BRACE S/M/L/XL', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'KNEE BRACE S/M/L/XL');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'FOLEYS CATHAtHER 14F', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'FOLEYS CATHAtHER 14F');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'UROMETER', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'UROMETER');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'LOX GELLY 2%', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'LOX GELLY 2%');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ESMARCH 6INCH', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ESMARCH 6INCH');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Consumables - THR', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Consumables - THR');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'HIP U BAR  DRAPE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'HIP U BAR  DRAPE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'IOBAN 6640/6650', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'IOBAN 6640/6650');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SURGICAL BLADE 10 /22/20', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SURGICAL BLADE 10 /22/20');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ROMO VAC 12FR / 14FR', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ROMO VAC 12FR / 14FR');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SYRINGE 50CC,20CC , 10CC', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SYRINGE 50CC,20CC , 10CC');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'INJ :TRICORT 40 MG', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'INJ :TRICORT 40 MG');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'C-ARM COVER PLASTIC', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'C-ARM COVER PLASTIC');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'RIBBEN GAUZE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'RIBBEN GAUZE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ETHIBOND NO 2  4843', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ETHIBOND NO 2  4843');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SURGEON CAP', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SURGEON CAP');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'DINO PLASTER', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'DINO PLASTER');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'FOLEYS CATHETER 14FR /16FR', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'FOLEYS CATHETER 14FR /16FR');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'URO BAG', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'URO BAG');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', '2 % LOX GELLY', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = '2 % LOX GELLY');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Spencer Wells Forceps Straight 8"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Spencer Wells Forceps Straight 8"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Ortho Interlocking Set (complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Ortho Interlocking Set (complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Ortho Pelvic Instrument Set (complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Ortho Pelvic Instrument Set (complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Ortho Small Surgery List (complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Ortho Small Surgery List (complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Mini Fragment Set (complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Mini Fragment Set (complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Mini Fragment Set 2 (Screw Driver 4.5mm)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Mini Fragment Set 2 (Screw Driver 4.5mm)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SS Wire Instruments Set (complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SS Wire Instruments Set (complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Additional Instruments Set (Ortho)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Additional Instruments Set (Ortho)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'K-Wire 1.8mm', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'K-Wire 1.8mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'K-Wire 2.0mm', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'K-Wire 2.0mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'K-Wire 2.5mm', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'K-Wire 2.5mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'K-Wire 3.0mm', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'K-Wire 3.0mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SS Wire 16G', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SS Wire 16G');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SS Wire 18G', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SS Wire 18G');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SS Wire 20G', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SS Wire 20G');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Consumables - ORIF', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Consumables - ORIF');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ORTHO  MAJOR DRAPE', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ORTHO  MAJOR DRAPE');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'NS FREEFLEX POUCH 500ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'NS FREEFLEX POUCH 500ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'POVODINE 10% W/V 500ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'POVODINE 10% W/V 500ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'IOBAN 6640', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'IOBAN 6640');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SURGICAL BLADE 10 / 11/20', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SURGICAL BLADE 10 / 11/20');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SYRINGE 50CC,20CC', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SYRINGE 50CC,20CC');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'C-ARM COVER', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'C-ARM COVER');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'MONOCRYL 3.0  1326', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'MONOCRYL 3.0  1326');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ROLLER BANDAGE  4 /6INCH', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ROLLER BANDAGE  4 /6INCH');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'SOFT ROLL 4/6INCH', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'SOFT ROLL 4/6INCH');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'CRAPE BANDAGE 4/6INCH', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'CRAPE BANDAGE 4/6INCH');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'DRESSING PAD', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'DRESSING PAD');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'POVODINE 7.5% 500ML', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'POVODINE 7.5% 500ML');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'MALE CAP / FEMALE CAP', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'MALE CAP / FEMALE CAP');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'EXAMINATION GLOVES', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'EXAMINATION GLOVES');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'ARM SLING POUCH S.M.L.XL.', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ARM SLING POUCH S.M.L.XL.');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'TEGADERM 8591', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'TEGADERM 8591');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'S MARCH 6INCH', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'S MARCH 6INCH');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'POP 4 INCH /6INCH', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'POP 4 INCH /6INCH');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'CUTTING & DISSECTION (open backup)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'CUTTING & DISSECTION (open backup)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'LSCS Set (complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'LSCS Set (complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Normal Delivery Set (complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Normal Delivery Set (complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'D & C Set (complete)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'D & C Set (complete)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Spencer Wells Forceps Curved 6"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Spencer Wells Forceps Curved 6"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Spencer Wells Forceps Curved 8"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Spencer Wells Forceps Curved 8"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Kocher Forceps Straight 8"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Kocher Forceps Straight 8"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Vulsellum Forceps Straight 9.5"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Vulsellum Forceps Straight 9.5"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Baby Allis Tissue Forceps', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Baby Allis Tissue Forceps');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Sims Vaginal Speculum Small', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Sims Vaginal Speculum Small');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Sims Vaginal Speculum Medium', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Sims Vaginal Speculum Medium');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Sims Vaginal Speculum Large', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Sims Vaginal Speculum Large');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Sims Graduated Uterine Sound 13"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Sims Graduated Uterine Sound 13"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Hegar Uterine Dilators Set 3-18mm', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Hegar Uterine Dilators Set 3-18mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Uterine Curette Sharp Fig.2', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Uterine Curette Sharp Fig.2');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Uterine Curette Sharp Fig.4', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Uterine Curette Sharp Fig.4');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Uterine Curette Blunt Fig.2', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Uterine Curette Blunt Fig.2');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Uterine Curette Blunt Fig.4', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Uterine Curette Blunt Fig.4');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Polypus & Ovum Forceps 10"', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Polypus & Ovum Forceps 10"');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Uterine Depressor', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Uterine Depressor');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'Balfour Self-Retaining Retractor', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Balfour Self-Retaining Retractor');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'instrument', 'VERIFIED from Lifelinx: 35 items', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'VERIFIED from Lifelinx: 35 items');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'General 30° 10mm', 'Mivonix', '30°, 10mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'General 30° 10mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'General 30° 5mm', 'Mivonix', '30°, 5mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'General 30° 5mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'ENT 0° 4mm', 'Mivonix', '0°, 4mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ENT 0° 4mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'ENT 30° 4mm', 'Mivonix', '30°, 4mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'ENT 30° 4mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'Urology 30° 4mm', 'Hopkins', '30°, 4mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Urology 30° 4mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'Urology 0° 4mm', 'Hopkins', '0°, 4mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Urology 0° 4mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'Urology 30° 4mm', 'Mivonix', '30°, 4mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Urology 30° 4mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'Urology Nephroscope Paediatric', 'Karl Storz', 'Nephroscope, Paediatric', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Urology Nephroscope Paediatric');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'Urology Cystoscope Paediatric', 'Karl Storz', 'Cystoscope, Paediatric', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Urology Cystoscope Paediatric');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'Urology UreteroScope 6° 9.5mm', 'Mivonix', 'UreteroScope 6°, 9.5mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Urology UreteroScope 6° 9.5mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'Urology UreteroScope 6° 7mm', 'Mivonix', 'UreteroScope 6°, 7mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Urology UreteroScope 6° 7mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'OBGYN Hysteroscope 2.9mm', 'Mivonix', 'Hysteroscope, 2.9mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'OBGYN Hysteroscope 2.9mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laparoscope', 'OBGYN Hysteroscope 4mm', 'Mivonix', 'Hysteroscope, 4mm', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'OBGYN Hysteroscope 4mm');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'tower', 'Stryker Lap Tower', 'Stryker', NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Stryker Lap Tower');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'laser', '200W Holmium Laser', NULL, '200W', TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = '200W Holmium Laser');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'energy_source', 'Covidien Cautery (monopolar)', 'Covidien', NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Covidien Cautery (monopolar)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'energy_source', 'Covidien Ligasure', 'Covidien', NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Covidien Ligasure');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'surgical_equipment', 'energy_source', 'Ethicon Focus Harmonic', 'Ethicon', NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Ethicon Focus Harmonic');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'infrastructure', 'lighting', 'OT Light (ceiling)', NULL, NULL, FALSE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'OT Light (ceiling)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'infrastructure', 'table', 'OT Operating Table', NULL, NULL, FALSE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'OT Operating Table');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'infrastructure', 'anaesthesia', 'Anaesthesia Workstation', NULL, NULL, FALSE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Anaesthesia Workstation');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'sharps', 'Scalpel Blade #15', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Scalpel Blade #15');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'sharps', 'Scalpel Blade #11', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Scalpel Blade #11');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'sharps', 'Scalpel Blade #10', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Scalpel Blade #10');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'drapes', 'Surgical Drape Pack', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Surgical Drape Pack');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'drapes', 'Sterile Gown', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Sterile Gown');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'drapes', 'Sterile Gloves (pair)', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Sterile Gloves (pair)');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'sutures', 'Vicryl 2-0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Vicryl 2-0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'sutures', 'Vicryl 3-0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Vicryl 3-0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'sutures', 'Prolene 3-0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Prolene 3-0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'sutures', 'Chromic Catgut 3-0', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Chromic Catgut 3-0');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'cautery', 'Monopolar Cautery Pencil', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Monopolar Cautery Pencil');
  INSERT INTO equipment_inventory (hospital_id, category, subcategory, item_label, brand, size_spec, is_rentable, notes) SELECT v_ehrc_id, 'consumable', 'cautery', 'Diathermy Grounding Pad', NULL, NULL, TRUE, NULL WHERE NOT EXISTS (SELECT 1 FROM equipment_inventory WHERE hospital_id = v_ehrc_id AND item_label = 'Diathermy Grounding Pad');

  RAISE NOTICE 'equipment_inventory seeded for EHRC';
END
$seed$;

-- 4. Marker
INSERT INTO _migrations (name, applied_at)
VALUES ('25-apr-equipment-inventory', NOW())
ON CONFLICT (name) DO NOTHING;

-- 5. Sanity check
DO $chk$
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM equipment_inventory
   WHERE hospital_id = (SELECT id FROM hospitals WHERE slug='ehrc');
  RAISE NOTICE 'equipment_inventory has % rows for EHRC', v_count;
END
$chk$;
