-- ================================================================
-- migration-reference-doctors-specialty.sql
-- 24 Apr 2026 (Commit B of Marketing Handoff refactor)
--
-- Populates reference_doctors.specialty with canonical values from
-- the 'Surgeon + Specialty' CSV. 217 doctors, 38 distinct canonical
-- specialties (16 surgical + 22 non-surgical).
--
-- Idempotent — rerunning reapplies the same values. Match is by
-- lower(full_name) + EHRC hospital_id.
-- ================================================================

WITH mapping (name, specialty) AS (VALUES
  ('A Nagaraja Rao', 'Urology'),
  ('A Poornima', 'ICU'),
  ('Abhinandhan V', 'Emergency'),
  ('Abrar Mohammed', 'Orthopedics'),
  ('Adarsh Malagouda Patil', 'General Surgery'),
  ('Ajay P', 'Radiation Oncology'),
  ('Akshay Dhanda', 'Orthopedics'),
  ('Akshay Shetty', 'Orthopedics'),
  ('Amisha Shree Reddy', 'Wards'),
  ('Amit D Galgali', 'Paediatric Haemato-Oncology'),
  ('Amit Patil', 'Urology'),
  ('Amith Kamath', 'Orthopedics'),
  ('Amresh S Bhaganagare', 'Neurology'),
  ('Anagha Nawal', 'Obstetrics & Gynecology'),
  ('Ananya Puttaraju', 'Orthopedics'),
  ('Anil Kumar T', 'Urology'),
  ('Anil S Mehta', 'General Surgery'),
  ('Animesh Banerjee', 'ENT'),
  ('Anitha M', 'Plastic Surgery'),
  ('Anjali R Nath', 'Pulmonology'),
  ('Anjani Dixit', 'Obstetrics & Gynecology'),
  ('Ankit P Bhojani', 'Internal Medicine'),
  ('Anthony Vijay Pais', 'Oncology'),
  ('Anusha S', 'Dermatology'),
  ('Anusham Anantharam Ananthasayanan', 'Plastic Surgery'),
  ('Arun Kumar G C', 'Orthopedics'),
  ('Arun Raykar', 'ENT'),
  ('Avinash Parthasarathy', 'Orthopedics'),
  ('B Sunil', 'Neurosurgery'),
  ('Basavaraj Utagi', 'Cardiology'),
  ('Basharat Nadeem', 'ENT'),
  ('Bharathiraja Thillainatesan', 'General Surgery'),
  ('Brahmavara Shamburao Ramesh', 'General Surgery'),
  ('C Manoj', 'Internal Medicine'),
  ('Chaitanya B S', 'General Surgery'),
  ('Chandrashekarareddy S A', 'General Surgery'),
  ('Channappagoud Nadagoud', 'Radiology'),
  ('Chethan Patil S', 'Orthopedics'),
  ('Darshan Gowda A', 'ICU'),
  ('Davy Jacob Olakkengil', 'Orthopedics'),
  ('Deepak L', 'Anaesthesia'),
  ('Deevish Nooji Dinakara', 'Plastic Surgery'),
  ('Devanand Hulmani', 'Orthopedics'),
  ('Devaprashanth M', 'General Surgery'),
  ('Divya Badanidiyur', 'ENT'),
  ('Divya R', 'Ophthalmology'),
  ('Dr.Kiran Joshy', 'Dermatology'),
  ('Dr.Lokesh.K.N', 'Medical Oncology'),
  ('Dr.Niranjan P', 'General Surgery'),
  ('Dr.Pramod Chakrapani Adiga', 'Urology'),
  ('Dr.Sharath Kumar', 'Rheumatology'),
  ('Dr.Shashidhar K P', 'Vascular Surgery'),
  ('Farhan Ali', 'General Surgery'),
  ('Fasahath Faraz Khan', 'ICU'),
  ('G Nivedita', 'Pathology'),
  ('G R Manjunath', 'Urology'),
  ('G S Prajwal', 'Orthopedics'),
  ('Gaurav Sen', 'Orthopedics'),
  ('Gautham Shankar', 'Emergency'),
  ('Girish K N', 'Anaesthesia'),
  ('Girish Namagondlu Seetharamaiah', 'Nephrology'),
  ('Gladson Guddappa Uchil', 'ENT'),
  ('H Kishore', 'Orthopedics'),
  ('H Santosh', 'Neurology'),
  ('Harini B S', 'Plastic Surgery'),
  ('Harish Kumar Hanumappa', 'Surgical Oncology'),
  ('Harish Puranik', 'Orthopedics'),
  ('Harsha MT', 'Radiology'),
  ('Harshan K S', 'Radiology'),
  ('Harshitha', 'Psychiatry'),
  ('Heba Fathima', 'Wards'),
  ('Hitesh S Byatroy', 'Orthopedics'),
  ('Hrishikesh Bhowmick', 'Oral & Maxillofacial Surgery'),
  ('Jagadeesh P C', 'Orthopedics'),
  ('Jagdish Chattnalli', 'Neurosurgery'),
  ('Jaidev S', 'Neurosurgery'),
  ('Jeevasri A L', 'Anaesthesia'),
  ('Karthik K S', 'Orthopedics'),
  ('Kaushik Y S', 'Orthopedics'),
  ('Khaja Javed Khan', 'Anaesthesia'),
  ('Kiran Joshy', 'Dermatology'),
  ('Kirantej Daggupati', 'Orthopedics'),
  ('Kushal Kumar T R', 'Urology'),
  ('Mahendra Jain', 'Urology'),
  ('Mala Dharmalingam', 'Endocrinology'),
  ('Manish Kumar Singh', 'Oral & Maxillofacial Surgery'),
  ('Manjunath S', 'Oral & Maxillofacial Surgery'),
  ('Manoj Kumar S', 'Orthopedics'),
  ('Manu C Bharadwaj', 'Paediatric Surgery'),
  ('Manukumar H', 'Anaesthesia'),
  ('Mayur Nair', 'ENT'),
  ('Megha H Chouhan', 'Obstetrics & Gynecology'),
  ('Mir Zeeshan Ali', 'General Surgery'),
  ('Mithun Oswal & Team', 'Orthopedics'),
  ('Mohammad Sadat Ur Rahman', 'Orthopedics'),
  ('Mohammed Furkan M', 'General Surgery'),
  ('Myneedi Vineela', 'Obstetrics & Gynecology'),
  ('Nakul', 'Orthopedics'),
  ('Navaneeth Y', 'Oral & Maxillofacial Surgery'),
  ('Naveen Kumar A G', 'ENT'),
  ('Nayar Sajeet Gopinathan', 'General Surgery'),
  ('Nipun Channabasappa Annigeri', 'Urology'),
  ('Niranjana Rajagopal', 'Neurosurgery'),
  ('Nishath Fathima', 'General Surgery'),
  ('Nishita Das', 'Pediatrics'),
  ('Nivedita Jha', 'Obstetrics & Gynecology'),
  ('Niyaz Ahmed', 'General Surgery'),
  ('P V Sudharasan', 'Neurosurgery'),
  ('Poornesh Gowda M S', 'Orthopedics'),
  ('Poornima Parasuraman', 'General Surgery'),
  ('Prabhudev M Salanki', 'Urology'),
  ('Pradeep', 'Orthopedics'),
  ('Prajeth S S', 'ICU'),
  ('Prajna Shekar B', 'Wards'),
  ('Prajwal Ramegowda', 'Orthopedics'),
  ('Pramod Mahesh', 'Orthopedics'),
  ('Pramukh N', 'Oral & Maxillofacial Surgery'),
  ('Prashanth Nagaraj', 'Orthopedics'),
  ('Prashanth Nagesh Tavane', 'Oral & Maxillofacial Surgery'),
  ('Prashantkumar', 'Orthopedics'),
  ('Prateek Patil', 'General Surgery'),
  ('Prathap U S', 'Orthopedics'),
  ('Praveen S Battepati', 'Orthopedics'),
  ('Preetham N', 'Orthopedics'),
  ('Premkumar', 'General Surgery'),
  ('Premkumar A', 'General Surgery'),
  ('Prerana N', 'Obstetrics & Gynecology'),
  ('Priyanka Akhilesh Sali', 'General Surgery'),
  ('Puneeth', 'Orthopedics'),
  ('Puneeth B S', 'Gastroenterology'),
  ('Puneeth Thalasta', 'General Surgery'),
  ('Putta Kemparaju KV', 'Orthopedics'),
  ('R Ayyappa', 'Emergency'),
  ('R Chethan', 'Dentistry'),
  ('R K Swathi', 'ENT'),
  ('R Prathik', 'Urology'),
  ('R Ravindran', 'Orthopedics'),
  ('R Sunil Kumar', 'Pediatrics'),
  ('Raghunath', 'Pain & Palliative Care'),
  ('Ragul', 'Emergency'),
  ('Rahul P', 'Orthopedics'),
  ('Rajan G', 'Anaesthesia'),
  ('Rajat B N', 'Orthopedics'),
  ('Rajeev Pullagura', 'General Surgery'),
  ('Rajendra Prasad', 'ENT'),
  ('Rakesh Kumar', 'Orthopedics'),
  ('Rakshit Babaji', 'General Surgery'),
  ('Rakshita Kamath', 'ENT'),
  ('Rakshith Chakravarthy H Y', 'Orthopedics'),
  ('Ravi Sachidananda', 'ENT'),
  ('Rebecca Susan Gladvin', 'Emergency'),
  ('Rhithu Sri', 'Wards'),
  ('Rohith M', 'Surgical Gastroenterology'),
  ('Roopesh Narayanachary', 'Surgical Oncology'),
  ('Roshan Kumar Bhandari', 'Orthopedics'),
  ('S S Shreyas', 'Oral & Maxillofacial Surgery'),
  ('Sachin C. Thagadur', 'Orthopedics'),
  ('Sachin S', 'General Surgery'),
  ('Sagar Srinivas K', 'Anaesthesia'),
  ('Sai Shruti Rai', 'General Surgery'),
  ('Sangeetha Siva', 'General Surgery'),
  ('Sanjeev MN', 'Orthopedics'),
  ('Satyajeeth R', 'Orthopedics'),
  ('Sharil Hegde P', 'Pediatrics'),
  ('Shashank N P', 'Anaesthesia'),
  ('Shashidhara Naik C', 'General Surgery'),
  ('Shilpa Rajendran', 'ICU'),
  ('Shilpashree N', 'Obstetrics & Gynecology'),
  ('Shishira S Ranade', 'Plastic Surgery'),
  ('Shishirakumar A Goudar', 'Neurology'),
  ('Shiva Kumar', 'General Surgery'),
  ('Shravya Madhu', 'Obstetrics & Gynecology'),
  ('Shreekantha K S', 'Orthopedics'),
  ('Shwetha B M', 'Plastic Surgery'),
  ('Siddharth M', 'Vascular Surgery'),
  ('Smita Hegde', 'ENT'),
  ('Soeshyante Babu', 'General Surgery'),
  ('Soujanya Mahadevaiah', 'Plastic Surgery'),
  ('Sounjanya Mahadevaiah', 'Plastic Surgery'),
  ('Sravan C P S', 'Vascular Surgery'),
  ('Sriharee Kulkarni', 'Internal Medicine'),
  ('Srikanth K N', 'General Surgery'),
  ('Srinivasan Seetharam', 'ENT'),
  ('Srishti Shailesh Ghorpade', 'Oral & Maxillofacial Surgery'),
  ('Subash K G', 'Surgical Gastroenterology'),
  ('Suhas Thodata Ravi', 'Plastic Surgery'),
  ('Sujay BR', 'General Surgery'),
  ('Sunil Kumar. V', 'General Surgery'),
  ('Swathi Iyengar Singh', 'Oral & Maxillofacial Surgery'),
  ('Tarun Desai', 'Orthopedics'),
  ('Trishi Chandan Kulkarni', 'Anaesthesia'),
  ('Uday Ravi', 'General Surgery'),
  ('Udaybhaskar M', 'Urology'),
  ('V Devendran', 'General Surgery'),
  ('Vaibhav Shivram Lokhande', 'Physiatry'),
  ('Varun Kumar J', 'General Surgery'),
  ('Vasudev Prabhu', 'Orthopedics'),
  ('Vedaprakash M.K', 'Orthopedics'),
  ('Veeresh N', 'Orthopedics'),
  ('Vikas Chavan', 'Orthopedics'),
  ('Vinay M H', 'Urology'),
  ('Vinit Oswal', 'Orthopedics'),
  ('Vishal Naik', 'General Surgery'),
  ('Vishnu Kurpad', 'Surgical Oncology'),
  ('Vishrutha L N', 'Wards'),
  ('Vishwajeeth Pai', 'Medical Oncology'),
  ('Vivek A', 'Orthopedics'),
  ('Vivek P Ksheerasagar', 'Orthopedics'),
  ('Vivekanand Hiremath', 'Urology'),
  ('Vivekanand N Bhat', 'General Surgery'),
  ('Vybhav Deraje', 'Plastic Surgery'),
  ('Waquar Ahmed', 'ICU'),
  ('Yashika S', 'Obstetrics & Gynecology'),
  ('Yathiraj Bharatoor Ramdas', 'Orthopedics'),
  ('Yeshwath R', 'Surgical Oncology'),
  ('Zubair', 'Physiotherapy'),
  ('Zubair Ahmed', 'Surgical Oncology')
)
UPDATE reference_doctors rd
SET specialty = mapping.specialty, updated_at = now()
FROM mapping, hospitals h
WHERE lower(rd.full_name) = lower(mapping.name)
  AND rd.primary_hospital_id = h.id
  AND h.slug = 'ehrc';

-- Verify:
-- SELECT specialty, count(*) FROM reference_doctors GROUP BY specialty ORDER BY 2 DESC;
