-- ================================================================
-- migration-reference-doctors.sql
-- 24 Apr 2026
--
-- Adds a reference roster of external/non-app-user doctors so the
-- Marketing Handoff 'Admitting Doctor' picker can populate from a
-- real list without polluting the profiles (auth) table.
--
-- Idempotent — safe to re-run. All inserts use ON CONFLICT DO NOTHING
-- keyed off (lower(full_name), primary_hospital_id).
-- ================================================================

CREATE TABLE IF NOT EXISTS reference_doctors (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  association text CHECK (association IN (
    'full_time_consultant', 'visiting_consultant', 'part_time_consultant',
    'full_time_employee', 'part_time'
  )),
  specialty text,
  primary_hospital_id uuid REFERENCES hospitals(id) ON DELETE SET NULL,
  source text NOT NULL DEFAULT 'manual',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Unique-on-name-and-hospital. Using COALESCE to treat NULL hospital as its own bucket.
CREATE UNIQUE INDEX IF NOT EXISTS ux_reference_doctors_name_hosp
  ON reference_doctors (lower(full_name), COALESCE(primary_hospital_id, '00000000-0000-0000-0000-000000000000'::uuid));

CREATE INDEX IF NOT EXISTS idx_reference_doctors_active_name
  ON reference_doctors (full_name) WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_reference_doctors_hospital
  ON reference_doctors (primary_hospital_id) WHERE primary_hospital_id IS NOT NULL;

-- ────────────────────────────────────────────────────────────────
-- Seed: 217 EHRC doctors from HR staff data (24 Apr 2026).
-- Each row scoped to EHRC hospital_id (looked up by slug).
-- ────────────────────────────────────────────────────────────────

WITH ehrc AS (SELECT id FROM hospitals WHERE slug = 'ehrc')
INSERT INTO reference_doctors (full_name, association, primary_hospital_id, source)
SELECT v.full_name, v.association, ehrc.id, 'staff_csv_apr2026'
FROM ehrc, (VALUES
  ('A Nagaraja Rao', NULL),
  ('A Poornima', NULL),
  ('Abhinandhan V', 'full_time_consultant'),
  ('Abrar Mohammed', 'visiting_consultant'),
  ('Adarsh Malagouda Patil', 'visiting_consultant'),
  ('Ajay P', NULL),
  ('Akshay Dhanda', NULL),
  ('Akshay Shetty', NULL),
  ('Amisha Shree Reddy', NULL),
  ('Amit D Galgali', NULL),
  ('Amit Patil', NULL),
  ('Amith Kamath', 'visiting_consultant'),
  ('Amresh S Bhaganagare', NULL),
  ('Anagha Nawal', NULL),
  ('Ananya Puttaraju', NULL),
  ('Anil Kumar T', NULL),
  ('Anil S Mehta', NULL),
  ('Animesh Banerjee', 'full_time_employee'),
  ('Anitha M', NULL),
  ('Anjali R Nath', NULL),
  ('Anjani Dixit', NULL),
  ('Ankit P Bhojani', 'part_time_consultant'),
  ('Anthony Vijay Pais', NULL),
  ('Anusha S', 'visiting_consultant'),
  ('Anusham Anantharam Ananthasayanan', 'visiting_consultant'),
  ('Arun Kumar G C', NULL),
  ('Arun Raykar', NULL),
  ('Avinash Parthasarathy', NULL),
  ('B Sunil', NULL),
  ('Basavaraj Utagi', 'visiting_consultant'),
  ('Basharat Nadeem', NULL),
  ('Bharathiraja Thillainatesan', NULL),
  ('Brahmavara Shamburao Ramesh', NULL),
  ('C Manoj', NULL),
  ('Chaitanya B S', 'full_time_consultant'),
  ('Chandrashekarareddy S A', NULL),
  ('Channappagoud Nadagoud', NULL),
  ('Chethan Patil S', NULL),
  ('Darshan Gowda A', NULL),
  ('Davy Jacob Olakkengil', NULL),
  ('Deepak L', NULL),
  ('Deevish Nooji Dinakara', NULL),
  ('Devanand Hulmani', NULL),
  ('Devaprashanth M', NULL),
  ('Divya Badanidiyur', NULL),
  ('Divya R', NULL),
  ('Dr.Kiran Joshy', NULL),
  ('Dr.Lokesh.K.N', NULL),
  ('Dr.Niranjan P', NULL),
  ('Dr.Pramod Chakrapani Adiga', NULL),
  ('Dr.Sharath Kumar', NULL),
  ('Dr.Shashidhar K P', NULL),
  ('Farhan Ali', NULL),
  ('Fasahath Faraz Khan', 'full_time_consultant'),
  ('G Nivedita', 'full_time_consultant'),
  ('G R Manjunath', NULL),
  ('G S Prajwal', NULL),
  ('Gaurav Sen', NULL),
  ('Gautham Shankar', 'full_time_consultant'),
  ('Girish K N', NULL),
  ('Girish Namagondlu Seetharamaiah', 'part_time_consultant'),
  ('Gladson Guddappa Uchil', NULL),
  ('H Kishore', NULL),
  ('H Santosh', NULL),
  ('Harini B S', NULL),
  ('Harish Kumar Hanumappa', NULL),
  ('Harish Puranik', NULL),
  ('Harsha MT', NULL),
  ('Harshan K S', 'part_time_consultant'),
  ('Harshitha', NULL),
  ('Heba Fathima', 'full_time_consultant'),
  ('Hitesh S Byatroy', NULL),
  ('Hrishikesh Bhowmick', NULL),
  ('Jagadeesh P C', NULL),
  ('Jagdish Chattnalli', NULL),
  ('Jaidev S', NULL),
  ('Jeevasri A L', 'full_time_consultant'),
  ('Karthik K S', 'full_time_consultant'),
  ('Kaushik Y S', NULL),
  ('Khaja Javed Khan', NULL),
  ('Kiran Joshy', 'visiting_consultant'),
  ('Kirantej Daggupati', NULL),
  ('Kushal Kumar T R', NULL),
  ('Mahendra Jain', NULL),
  ('Mala Dharmalingam', NULL),
  ('Manish Kumar Singh', NULL),
  ('Manjunath S', NULL),
  ('Manoj Kumar S', NULL),
  ('Manu C Bharadwaj', NULL),
  ('Manukumar H', 'full_time_consultant'),
  ('Mayur Nair', NULL),
  ('Megha H Chouhan', NULL),
  ('Mir Zeeshan Ali', NULL),
  ('Mithun Oswal', NULL),
  ('Mohammad Sadat Ur Rahman', 'full_time_consultant'),
  ('Mohammed Furkan M', NULL),
  ('Myneedi Vineela', 'full_time_consultant'),
  ('Nakul', NULL),
  ('Navaneeth Y', NULL),
  ('Naveen Kumar A G', NULL),
  ('Nayar Sajeet Gopinathan', 'part_time_consultant'),
  ('Nipun Channabasappa Annigeri', NULL),
  ('Niranjana Rajagopal', NULL),
  ('Nishath Fathima', NULL),
  ('Nishita Das', 'part_time'),
  ('Nivedita Jha', 'part_time_consultant'),
  ('Niyaz Ahmed', NULL),
  ('P V Sudharasan', NULL),
  ('Poornesh Gowda M S', NULL),
  ('Poornima Parasuraman', 'full_time_consultant'),
  ('Prabhudev M Salanki', NULL),
  ('Pradeep', NULL),
  ('Prajeth S S', 'full_time_consultant'),
  ('Prajna Shekar B', 'full_time_consultant'),
  ('Prajwal Ramegowda', NULL),
  ('Pramod Mahesh', NULL),
  ('Pramukh N', NULL),
  ('Prashanth Nagaraj', 'full_time_consultant'),
  ('Prashanth Nagesh Tavane', NULL),
  ('Prashantkumar', NULL),
  ('Prateek Patil', NULL),
  ('Prathap U S', NULL),
  ('Praveen S Battepati', NULL),
  ('Preetham N', NULL),
  ('Premkumar', NULL),
  ('Premkumar A', 'visiting_consultant'),
  ('Prerana N', NULL),
  ('Priyanka Akhilesh Sali', NULL),
  ('Puneeth', NULL),
  ('Puneeth B S', 'part_time'),
  ('Puneeth Thalasta', NULL),
  ('Putta Kemparaju KV', NULL),
  ('R Ayyappa', 'full_time_consultant'),
  ('R Chethan', NULL),
  ('R K Swathi', NULL),
  ('R Prathik', NULL),
  ('R Ravindran', NULL),
  ('R Sunil Kumar', 'visiting_consultant'),
  ('Raghunath', NULL),
  ('Ragul', 'full_time_consultant'),
  ('Rahul P', 'visiting_consultant'),
  ('Rajan G', NULL),
  ('Rajat B N', NULL),
  ('Rajeev Pullagura', NULL),
  ('Rajendra Prasad', NULL),
  ('Rakesh Kumar', NULL),
  ('Rakshit Babaji', NULL),
  ('Rakshita Kamath', NULL),
  ('Rakshith Chakravarthy H Y', NULL),
  ('Ravi Sachidananda', NULL),
  ('Rebecca Susan Gladvin', 'full_time_consultant'),
  ('Rhithu Sri', 'full_time_consultant'),
  ('Rohith M', NULL),
  ('Roopesh Narayanachary', NULL),
  ('Roshan Kumar Bhandari', NULL),
  ('S S Shreyas', NULL),
  ('Sachin C. Thagadur', NULL),
  ('Sachin S', 'visiting_consultant'),
  ('Sagar Srinivas K', NULL),
  ('Sai Shruti Rai', NULL),
  ('Sangeetha Siva', NULL),
  ('Sanjeev MN', 'visiting_consultant'),
  ('Satyajeeth R', NULL),
  ('Sharil Hegde P', 'part_time'),
  ('Shashank N P', NULL),
  ('Shashidhara Naik C', NULL),
  ('Shilpa Rajendran', 'full_time_consultant'),
  ('Shilpashree N', NULL),
  ('Shishira S Ranade', NULL),
  ('Shishirakumar A Goudar', 'part_time_consultant'),
  ('Shiva Kumar', NULL),
  ('Shravya Madhu', NULL),
  ('Shreekantha K S', NULL),
  ('Shwetha B M', NULL),
  ('Siddharth M', NULL),
  ('Smita Hegde', 'visiting_consultant'),
  ('Soeshyante Babu', NULL),
  ('Soujanya Mahadevaiah', NULL),
  ('Sounjanya Mahadevaiah', NULL),
  ('Sravan C P S', NULL),
  ('Sriharee Kulkarni', 'part_time_consultant'),
  ('Srikanth K N', 'visiting_consultant'),
  ('Srinivasan Seetharam', NULL),
  ('Srishti Shailesh Ghorpade', NULL),
  ('Subash K G', NULL),
  ('Suhas Thodata Ravi', NULL),
  ('Sujay BR', 'visiting_consultant'),
  ('Sunil Kumar. V', NULL),
  ('Swathi Iyengar Singh', NULL),
  ('Tarun Desai', NULL),
  ('Trishi Chandan Kulkarni', 'full_time_consultant'),
  ('Uday Ravi', NULL),
  ('Udaybhaskar M', NULL),
  ('V Devendran', NULL),
  ('Vaibhav Shivram Lokhande', NULL),
  ('Varun Kumar J', NULL),
  ('Vasudev Prabhu', NULL),
  ('Vedaprakash M.K', NULL),
  ('Veeresh N', NULL),
  ('Vikas Chavan', 'visiting_consultant'),
  ('Vinay M H', NULL),
  ('Vinit Oswal', NULL),
  ('Vishal Naik', 'part_time'),
  ('Vishnu Kurpad', NULL),
  ('Vishrutha L N', NULL),
  ('Vishwajeeth Pai', NULL),
  ('Vivek A', NULL),
  ('Vivek P Ksheerasagar', NULL),
  ('Vivekanand Hiremath', NULL),
  ('Vivekanand N Bhat', NULL),
  ('Vybhav Deraje', NULL),
  ('Waquar Ahmed', 'full_time_consultant'),
  ('Yashika S', 'full_time_consultant'),
  ('Yathiraj Bharatoor Ramdas', NULL),
  ('Yeshwath R', NULL),
  ('Zubair', NULL),
  ('Zubair Ahmed', NULL)
) AS v(full_name, association)
ON CONFLICT (lower(full_name), COALESCE(primary_hospital_id, '00000000-0000-0000-0000-000000000000'::uuid)) DO NOTHING;

-- Verify:
-- SELECT association, count(*) FROM reference_doctors GROUP BY association ORDER BY 2 DESC;
