'use client';

// ============================================
// Rounds — Drafts Inbox (Sprint 1 Day 5)
//
// Skeletal inbox page for IP Coordinators to pick up draft surgical_cases
// generated by the Marketing Handoff hook and transition them to intake.
//
// Behind FEATURE_CASE_MODEL_ENABLED — if the flag is off, /api/cases returns
// an empty list and the page renders an informational empty state.
//
// Access: ip_coordinator + super_admin only. (Enforced client-side AND by the
// /api/cases/[id]/transition endpoint. This page is primarily a convenience UI.)
//
// Route: /drafts
// ============================================

import { useEffect, useState } from 'react';

interface DraftCase {
  id: string;
  hospital_id: string;
  hospital_slug: string;
  patient_thread_id: string;
  patient_name: string | null;
  handoff_submission_id: string | null;
  planned_procedure: string | null;
  planned_surgery_date: string | null;
  urgency: string | null;
  state: string;
  created_at: string;
  created_by: string | null;
}

export default function DraftsInboxPage() {
  const [cases, setCases] = useState<DraftCase[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [featureEnabled, setFeatureEnabled] = useState(true);

  const load = () => {
    setLoading(true);
    setError(null);
    fetch('/api/cases?state=draft&limit=100')
      .then((r) => r.json())
      .then((body) => {
        if (body?.success) {
          setCases(body.data || []);
          setFeatureEnabled(body.feature_enabled !== false);
        } else {
          setError(body?.error || 'Failed to load drafts');
        }
      })
      .catch((e) => setError(String(e)))
      .finally(() => setLoading(false));
  };

  useEffect(() => { load(); }, []);

  return (
    <main className="mx-auto max-w-6xl px-4 py-6">
      <header className="mb-6 flex items-start justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold text-gray-900">Drafts Inbox</h1>
          <p className="mt-1 text-sm text-gray-600">
            Surgical cases auto-created from Marketing Handoffs with surgery_planned.
            IP Coordinator picks up a draft → confirms with KE UHID → transitions to intake.
          </p>
        </div>
        <button
          type="button"
          onClick={load}
          disabled={loading}
          className="rounded-md border border-gray-300 bg-white px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-50"
        >
          {loading ? 'Refreshing…' : 'Refresh'}
        </button>
      </header>

      {!featureEnabled && (
        <div className="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">
          <strong>Feature-flagged:</strong> Case model is disabled (<code>FEATURE_CASE_MODEL_ENABLED</code> is
          not true). Drafts auto-creation and the inbox are inactive until the flag flips — planned for Sprint 2.
        </div>
      )}

      {error && (
        <div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-900">
          Error: {error}
        </div>
      )}

      {loading && <p className="text-sm text-gray-500">Loading…</p>}

      {!loading && !error && cases.length === 0 && featureEnabled && (
        <div className="rounded-lg border border-dashed border-gray-300 bg-gray-50 p-10 text-center">
          <p className="text-sm font-medium text-gray-900">No drafts waiting.</p>
          <p className="mt-1 text-xs text-gray-600">
            When Marketing submits a handoff with surgery_planned, a draft will appear here for pickup.
          </p>
        </div>
      )}

      {cases.length > 0 && (
        <ul className="space-y-2">
          {cases.map((c) => (
            <DraftRow key={c.id} c={c} onChanged={load} />
          ))}
        </ul>
      )}
    </main>
  );
}

function DraftRow({ c, onChanged }: { c: DraftCase; onChanged: () => void }) {
  const [expanded, setExpanded] = useState(false);
  const [kxUhid, setKxUhid] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const open = async () => {
    if (!kxUhid.trim()) {
      setError('KE UHID is required');
      return;
    }
    setSubmitting(true);
    setError(null);
    try {
      const res = await fetch(`/api/cases/${c.id}/transition`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          to_state: 'intake',
          kx_uhid: kxUhid.trim(),
          transition_reason: 'ip_coordinator_pickup',
        }),
      });
      const body = await res.json();
      if (!res.ok || !body.success) {
        throw new Error(body.error || `HTTP ${res.status}`);
      }
      onChanged();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <li className="rounded-lg border border-gray-200 bg-white p-4">
      <div className="flex items-center justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2 text-sm font-medium text-gray-900">
            <span>{c.patient_name || '(no name)'}</span>
            <span className="inline-flex items-center rounded bg-gray-100 px-1.5 py-0.5 text-xs font-normal text-gray-700">
              {c.hospital_slug?.toUpperCase()}
            </span>
            {c.urgency && (
              <span
                className={`inline-flex items-center rounded px-1.5 py-0.5 text-xs font-normal ${
                  c.urgency === 'emergency' ? 'bg-red-100 text-red-800' :
                  c.urgency === 'urgent' ? 'bg-orange-100 text-orange-800' :
                  'bg-blue-100 text-blue-800'
                }`}
              >
                {c.urgency}
              </span>
            )}
          </div>
          <p className="mt-0.5 text-xs text-gray-600">
            {c.planned_procedure || '(no procedure yet)'}
            {c.planned_surgery_date && ` · planned ${new Date(c.planned_surgery_date).toLocaleDateString()}`}
          </p>
          <p className="mt-0.5 text-xs text-gray-500">
            draft created {new Date(c.created_at).toLocaleString()}
          </p>
        </div>
        <button
          type="button"
          onClick={() => setExpanded(!expanded)}
          className="flex-shrink-0 rounded-md bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700"
        >
          {expanded ? 'Cancel' : 'Open draft'}
        </button>
      </div>

      {expanded && (
        <div className="mt-3 rounded-md bg-gray-50 p-3">
          <label htmlFor={`kx-${c.id}`} className="block text-xs font-medium text-gray-700">
            KE UHID (required to move to intake)
          </label>
          <div className="mt-1 flex gap-2">
            <input
              id={`kx-${c.id}`}
              type="text"
              value={kxUhid}
              onChange={(e) => setKxUhid(e.target.value)}
              placeholder="e.g. EH-00012345"
              className="flex-1 rounded-md border border-gray-300 px-3 py-1.5 text-sm focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500"
            />
            <button
              type="button"
              onClick={open}
              disabled={submitting || !kxUhid.trim()}
              className="rounded-md bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700 disabled:opacity-50"
            >
              {submitting ? 'Moving…' : 'Move to intake'}
            </button>
          </div>
          {error && <p className="mt-2 text-xs text-red-700">{error}</p>}
          <p className="mt-2 text-xs text-gray-500">
            This transitions the case from <code>draft</code> to <code>intake</code> and logs the UHID.
            Undoable via admin within 24 hours.
          </p>
        </div>
      )}
    </li>
  );
}
